### ISSUE TITLE
 Format all files before commit

### ISSUE THREAD

**Issue by luisalves00** [lipiridi/spotless-applier#12]
I usually use my personal custom formatting while coding or fixing issues, but before commit I need to execute spotlessApply before committing as the remote build process will check the formatting. Would be nice that the formatting is applied before commit.

Example:
![316267492-2e5845e2-7c55-4dc4-8bcb-d291111506e2](https://github.com/lipiridi/spotless-applier/assets/3064521/963ff6a5-3f09-43d4-9831-97886f5bd6f9)

**Comment by lipiridi** [comment]
The new version has been released at https://github.com/lipiridi/spotless-applier/releases/tag/v1.0.5.
JetBrains is currently reviewing the update, which may take up to 3 days, after which it will be available in the marketplace.
Please note that the compatible IntelliJ IDEA version has been increased to 241.

**Comment by luisalves00** [comment]
Great. Thanks.
