### ISSUE TITLE
Doesn't replace wildcard imports when used together with `google-java-format` IntelliJ plugin

### ISSUE THREAD

**Issue by Sax388** [lipiridi/spotless-applier#26]
I've read your comment https://github.com/diffplug/spotless/issues/649#issuecomment-1681075082 and thought that with these settings
![image](https://github.com/user-attachments/assets/d3480156-9f1b-4cb7-a4ca-d02f08fe813d)
the following would be replaced
```java
import io.opentelemetry.instrumentation.annotations.*;
```
but unfortunately it stays after running the command.

I've restarted the IDE after installing the plugin. I'm using IntelliJ IDEA 2024.2.1 with the latest plugin version 1.1.2.

**Comment by Sax388** [comment]
I've had a look at the code where you fetch the settings from the editor
https://github.com/lipiridi/spotless-applier/blob/9ab38a4dc9ddcc6cddaffdda3cf34c44ec57cc31/src/main/java/com/github/lipiridi/spotless/applier/SynchronousOptimizeImportsProcessor.java#L44
so I double checked if the number of classes before falling back to `*` was high enough:
![image](https://github.com/user-attachments/assets/f85742d7-074d-4eff-a33c-3e687ed8f2a9)

And then I saw that you even use temporary settings to overwrite this. How cool. Integer max value is also so much better than my meager `999` 😆 .

**Comment by Sax388** [comment]
I found the culprit. When I switch off the `google-java-format` plugin
![image](https://github.com/user-attachments/assets/894fded9-4cad-44c0-8b41-4ad99eef24ca)
then it works like a charm. Thanks a million for this wonderful plugin!

**Comment by lipiridi** [comment]
Hello @Sax388!
Sorry for the late response. I'm glad you solved the issue yourself!
I guess `google-java-format` plugin somehow forcibly overrides the config.
To be honest, I don't see the advantages to spent time resolving this,
