### ISSUE TITLE
Commit Check not working in IntelliJ IDEA 2024.3

### ISSUE THREAD

**Issue by b-heimann-senacor** [lipiridi/spotless-applier#32]
I recently updated to IntelliJ IDEA version 2024.3 and noticed that the pre-commit check **Reformat code with Spotless** is no longer available. This issue seems to be related to the introduction of "Advanced Commit Checks" in this version.

![Bildschirmfoto 2024-11-14 um 14 43 01](https://github.com/user-attachments/assets/05241faf-c52c-49cb-ad53-4451e09b5fc0)

I have used the commit check in the past, and it worked very well. The only concern I had previously was that when activated, the commit check was global and applied to all IntelliJ projects. This was occasionally problematic since I do not use Spotless for some of my projects, leading to errors caused by the commit check.

I would greatly appreciate a fix for this issue.

**Comment by henrylangenhoven** [comment]
Same in **Actions on save** section, the `Run spotless` option is missing in IntelliJ IDEA 2024.3

![image](https://github.com/user-attachments/assets/e90ab552-b6fc-4f53-a7b9-8f28297e8201)

**Comment by jlagerweij** [comment]
What seems to be happening is that the old version of the plugin is loade (version 1.0.4) which does not have a limit on which IntelliJ can load it. 

The sollution should be to release  a new version of the plugin with the latest IntelliJ configured in the gradle.properties:

`pluginUntilBuild=243.*`

**Comment by lipiridi** [comment]
Hello guys! @jlagerweij you are right. The simple unlimited version was loaded.
I see IntelliJ has introduced new async commit options, so I'll inspect the latest changes ASAP to build a new compatible version.

**Comment by lipiridi** [comment]
The new version is released - https://github.com/lipiridi/spotless-applier/releases/tag/v1.1.4
Expect it on the marketplace within two business days.

@b-heimann-senacor I also moved the pre-commit option state to the workspace settings (as it's done for other options). Hope your work will become more convenient 😃

**Comment by b-heimann-senacor** [comment]
Everything is working fine again with v1.14. Thank you! @jlagerweij
