### ISSUE TITLE
Doesn't work in complex workspace

### ISSUE THREAD

**Issue by 2-5** [lipiridi/spotless-applier#6]
When trying to use the plugin from a complex workspace with multiple projects I get an error:

```
/home/user/.sdkman/candidates/java/17.0.4.1-tem/bin/java
-Dmaven.multiModuleProjectDirectory=/home/user/x
-Djansi.passthrough=true
-DspotlessFiles=.home.user.x.src.common.src.main.java.x.common.TableName\.java
-Dmaven.home=/home/user/.sdkman/candidates/maven/3.9.4
-Dclassworlds.conf=/home/user/.sdkman/candidates/maven/3.9.4/bin/m2.conf
-Dmaven.ext.class.path=/snap/intellij-idea-community/454/plugins/maven/lib/maven-event-listener.jar
-javaagent:/snap/intellij-idea-community/454/lib/idea_rt.jar=40583:/snap/intellij-idea-community/454/bin
-Dfile.encoding=UTF-8
-classpath /home/user/.sdkman/candidates/maven/3.9.4/boot/plexus-classworlds-2.7.0.jar:
/home/user/.sdkman/candidates/maven/3.9.4/boot/plexus-classworlds.license org.codehaus.classworlds.Launcher
-Didea.version=2023.2.1
spotless:apply
```

```
[ERROR] No plugin found for prefix 'spotless' in the current project and in the plugin groups
[org.apache.maven.plugins, org.codehaus.mojo] available from the repositories
[local (/home/user/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
```

Trying the command used by the plugin in a terminal, but adding `-pl :x` to the command line (`x` is the project name) is enough to make it work.

**Comment by lipiridi** [comment]
Hi!
Thank you for your participation.
Yeah, currently the plugin doesn't support multi projects in one IDE instance.
Only multi module projects or when all projects are located inside one folder and that folder is opened as one project in the IDE.
Will investigate how to add supporting for the case you mentioned.

**Comment by lipiridi** [comment]
I had some time and investigated the issue. Unfortunately, I couldn't reproduce the issue (built the workspace using in your way). Every time, the plugin resolved the build tools and executed the task successfully.

Could you please share a screenshot of the project window? Additionally, a screenshot of the 'Select modules' window (Ctrl+Shift+Alt+;) would be helpful.

**Comment by 2-5** [comment]
I tried again the plugin and this time it seems to work without errors, I can't reproduce the error anymore.

There were a large number of pom changes on the project, java upgrade from 17 to 21, so whatever caused the incompatibility was probably changed.

I'll close the issue and reopen if I encounter it again.
