### ISSUE TITLE
Plugin not compatible with IntelliJ 2023.3 Build #IU-233.11799.241, built on December 2, 2023

### ISSUE THREAD

**Issue by neilg** [lipiridi/spotless-applier#8]
The plugin is not compatible the latest version of IntelliJ. 
![Screenshot_20231208_121405](https://github.com/lipiridi/spotless-applier/assets/563627/95582862-16d5-4a36-9305-416f46ea611b)

**Comment by lipiridi** [comment]
Hello! Thanks, I will update the plugin today.

**Comment by lipiridi** [comment]
New version is waiting for review (up to 1d), but you already can download it by direct link: https://plugins.jetbrains.com/plugin/22455-spotless-applier/versions/stable/452877
